### ISSUE TITLE
Add support for Django 2.2

### ISSUE THREAD

**Issue by radiac** [radiac/django-tagulous#71]
I've started [a branch to support Django 2.2](https://github.com/radiac/django-tagulous/tree/feature/django2.2), but there are some issues to resolve.

I'm short on time at the moment, so any contributions gratefully received.

**Comment by pascalvogel1992** [comment]
What are known issues with 2.2? Seems to work for me.

**Comment by mjpieters** [comment]
> What are known issues with 2.2? Seems to work for me.

Travis shows otherwise, see the [most recent build against the 2.2 branch](https://travis-ci.org/radiac/django-tagulous/builds/519803581).

**Comment by radiac** [comment]
The issue is an "unhashable type" error for certain operations.

There's a work in progress branch with 2.2 support which should fix this:

pip install -e git+https://github.com/radiac/django-tagulous.git@feature/django2.2#egg=django-tagulous

Hope to get the next release out in the next couple of weeks.

**Comment by mbaechtold** [comment]
This is awesome, I no longer get the `unhashable type` error.

**Comment by mebivek** [comment]
I tried installing the git branch for django 2.2 but the issue persisted..I must have missed something... for a quick fix i did a override on the delete() function of the model and set the tagulous field to None. And that helped me solve the issue for now

**Comment by radiac** [comment]
Release 0.14.1 is on pypi now which provides 2.2 support and should hopefully resolve this issue.

**Comment by mbaechtold** [comment]
Awesome 🎉 Thank you for the release.
